# SPDX-License-Identifier: MIT
#
# Fedora packaging for tradekit — pre-market screening + technical analysis CLI.
# Targets Fedora 44+ which ships Python 3.14.
#
# Build:
#   rpmbuild -ba packaging/tradekit.spec
#
# COPR build (after `copr-cli` configured):
#   copr-cli build davdunc/tradekit packaging/tradekit.spec
#
# Bundled libraries (Provides: bundled below): finvizfinance and ta are vendored
# at src/tradekit/_vendor/ because they are not yet packaged in Fedora repos.
# When upstream packages land in Fedora, drop the bundling and convert to
# Requires: lines.
#
# NOTE: Source0 resolves to the v%%{version} git tag. Tag the release before
# building — a Version here with no matching tag produces an unbuildable spec.

Name:           tradekit
Version:        0.3.0
Release:        1%{?dist}
Summary:        Pre-market screening, technical analysis, and trade setup evaluation

License:        MIT
URL:            https://github.com/davdunc/tradekit
Source0:        %{url}/archive/v%{version}/%{name}-%{version}.tar.gz

BuildArch:      noarch

BuildRequires:  python3-devel
BuildRequires:  pyproject-rpm-macros
# For %%check
BuildRequires:  python3-pytest

# Runtime deps (all available in Fedora 44 repos as of writing)
Requires:       python3 >= 3.14
Requires:       python3-yfinance
Requires:       python3-pandas
Requires:       python3-numpy
Requires:       python3-matplotlib >= 3.11.1
Requires:       python3-pydantic-settings
Requires:       python3-mcp
Requires:       python3-pyarrow
Requires:       python3-click
Requires:       python3-rich
Requires:       python3-pyyaml
Requires:       python3-requests
Requires:       python3-aiohttp
Requires:       python3-boto3
Requires:       python3-beautifulsoup4
Requires:       python3-lxml
Requires:       python3-dotenv

# Bundled (vendored) deps not yet in Fedora — versions tracked in
# src/tradekit/_vendor/<pkg>/VENDORED_VERSION
Provides:       bundled(python3-finvizfinance) = 1.3.0
Provides:       bundled(python3-ta) = 0.11.0

%description
tradekit is a personal trading-infrastructure CLI for pre-market screening,
technical analysis, sector/industry rotation snapshots, relative-strength
scoring, and bull/bear LLM-driven debate setups. It integrates with LifeOS
(formerly Personal AI Infrastructure / PAI), Finviz Elite, the Falcon screener,
and S3-compatible flat-file market data backends.

Commands: analyze, debate, gameplan, groups, init, levels, morning, news,
publish-review, regime, report, rs, sandwich, scan, second-day, watchlist,
weekly-review.

On-disk paths follow the XDG Base Directory specification — data under
$XDG_DATA_HOME, cache under $XDG_CACHE_HOME, state under $XDG_STATE_HOME. Two
paths are shared contracts with the rest of the Falcon suite and tolerate both
XDG and legacy locations; see docs/falcon-suite-compatibility.md.

%prep
%autosetup -p1


%generate_buildrequires
%pyproject_buildrequires


%build
%pyproject_wheel


%install
%pyproject_install
%pyproject_save_files tradekit

# Bash completion, generated by Click from the registered CLI. The entry point
# in %%{buildroot} cannot import the package without PYTHONPATH pointing at the
# not-yet-installed sitelib.
install -d -m 0755 %{buildroot}%{_datadir}/bash-completion/completions
PYTHONPATH=%{buildroot}%{python3_sitelib} \
    _TRADEKIT_COMPLETE=bash_source %{buildroot}%{_bindir}/tradekit \
    > %{buildroot}%{_datadir}/bash-completion/completions/tradekit

# Config skeleton. This is an example, not live config — it is documentation,
# so it is not marked %%config and carries no noreplace semantics.
install -d -m 0755 %{buildroot}%{_sysconfdir}/tradekit
install -m 0644 packaging/tradekit.conf.example \
    %{buildroot}%{_sysconfdir}/tradekit/tradekit.conf.example

# Systemd timer + service for daily groups snapshot
install -d -m 0755 %{buildroot}%{_userunitdir}
install -m 0644 packaging/tradekit-groups-daily.service \
    %{buildroot}%{_userunitdir}/tradekit-groups-daily.service
install -m 0644 packaging/tradekit-groups-daily.timer \
    %{buildroot}%{_userunitdir}/tradekit-groups-daily.timer


%check
# Every import in the package resolves against the installed tree.
%pyproject_check_import
# The CLI must produce help without raising. This is the smoke test that would
# have caught an unregistered command or a missing runtime dep, so it must be
# allowed to fail the build -- no `|| :`.
PYTHONPATH=%{buildroot}%{python3_sitelib} \
    %{buildroot}%{_bindir}/tradekit --help >/dev/null
%pytest -q


%files -f %{pyproject_files}
%license LICENSE
%license src/tradekit/_vendor/finvizfinance/LICENSE
%license src/tradekit/_vendor/ta/LICENSE
%doc README.md CHANGELOG.md
%{_bindir}/tradekit
%{_datadir}/bash-completion/completions/tradekit
%dir %{_sysconfdir}/tradekit
%{_sysconfdir}/tradekit/tradekit.conf.example
%{_userunitdir}/tradekit-groups-daily.service
%{_userunitdir}/tradekit-groups-daily.timer


%changelog
* Fri Aug 28 2026 David Duncan <davdunc@davidduncan.org> - 0.3.0-1
- Sync spec with the tree after four merged PRs; it had been stale at 0.1.0.
- Add Requires: python3-matplotlib >= 3.11.1 for round-trip blotter rendering.
- Correct the command list: add news, regime, sandwich, second-day.
- Rebrand Personal_AI_Infrastructure -> LifeOS in the description.
- Document the XDG Base Directory layout and the Falcon-suite path contracts.
- Move bash completion from %%{_sysconfdir}/bash_completion.d to
  %%{_datadir}/bash-completion/completions, the current Fedora location.
- Fix completion generation and the %%check smoke test: both invoked the
  buildroot entry point without PYTHONPATH and could never have imported the
  package.
- Stop masking %%check failures with `|| :`. A smoke test that cannot fail is
  not a test.
- Drop the %%config(noreplace) marking from tradekit.conf.example; an example
  file is documentation, not configuration.
- Drop the redundant BuildRequires: python3-pip (pyproject-rpm-macros pulls it).

* Tue Jul 14 2026 David Duncan <davdunc@davidduncan.org> - 0.2.0-1
- Session-anchored VWAP and the 15-Minute VWAP Sandwich detector.

* Sun May 03 2026 David Duncan <davdunc@davidduncan.org> - 0.1.0-1
- Initial Fedora packaging.
- Vendored finvizfinance 1.3.0 (MIT) and ta 0.11.0 (MIT) at
  src/tradekit/_vendor/ since they are not yet in Fedora repos.
- Ships /usr/bin/tradekit, bash completion, /etc/tradekit/ config skeleton,
  and user-level systemd timer for daily groups snapshot.
